name: Publish

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - run: npm install
      - run: npm run build

  bumpVersion:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 18
      - run: |
          npm version patch -m "Bump version to %s [skip ci]"
          git push --follow-tags

  publish:
    needs: bumpVersion
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
      - run: npm config set '//npm.pkg.github.com/:_authToken' "${GH_TOKEN}"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - run: npm publish
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
