name: Release

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm build

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      
      - uses: pnpm/action-setup@v2
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
          registry-url: https://npm.pkg.github.com/
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GH_TOKEN}}
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v3
      
      - name: Prepare repository
        run: git fetch --unshallow --tags

      - uses: pnpm/action-setup@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          pnpm release
