name: Verify changes

on: pull_request

jobs:
  autoVersion:
    name: Auto scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install dependencies
        run: npm install

      - name: Auto Label
        run: npm run autoLabel
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
